version: "3.7"
services:
  gateway:
    image: ${REGISTRY}/auction-gateway:${IMAGE_TAG}
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/html:/var/www/html:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - api

  frontend:
    image: ${REGISTRY}/auction-frontend:${IMAGE_TAG}
    restart: always

  api:
    image: ${REGISTRY}/auction-api:${IMAGE_TAG}
    restart: always
    depends_on:
      - api-php-fpm

  api-php-fpm:
    image: ${REGISTRY}/auction-api-php-fpm:${IMAGE_TAG}
    restart: always
    environment:
      APP_ENV: prod
      APP_DEBUG: 0
      DB_HOST: api-postgres
      DB_USER: app
      DB_PASSWORD_FILE: /run/secrets/api_db_password
      DB_NAME: app
      MAILER_HOST: ${API_MAILER_HOST}
      MAILER_PORT: ${API_MAILER_PORT}
      MAILER_USERNAME: ${API_MAILER_USERNAME}
      MAILER_PASSWORD_FILE: /run/secrets/api_mailer_password
      MAILER_ENCRYPTION: tls
      MAILER_FROM_EMAIL: ${API_MAILER_FROM_EMAIL}
      FRONTEND_URL: https://demo-auction.deworker.pro
      SENTRY_DSN_FILE: /run/secrets/sentry_dsn
      JWT_ENCRYPTION_KEY_FILE: /run/secrets/jwt_encryption_key
      JWT_PUBLIC_KEY_PATH: /run/secrets/jwt_public_key
      JWT_PRIVATE_KEY_PATH: /run/secrets/jwt_private_key
    secrets:
      - api_db_password
      - api_mailer_password
      - sentry_dsn
      - jwt_encryption_key
      - jwt_public_key
      - jwt_private_key

  api-php-cli:
    image: ${REGISTRY}/auction-api-php-cli:${IMAGE_TAG}
    environment:
      APP_ENV: prod
      APP_DEBUG: 0
      DB_HOST: api-postgres
      DB_USER: app
      DB_PASSWORD_FILE: /run/secrets/api_db_password
      DB_NAME: app
      MAILER_HOST: ${API_MAILER_HOST}
      MAILER_PORT: ${API_MAILER_PORT}
      MAILER_USERNAME: ${API_MAILER_USERNAME}
      MAILER_PASSWORD_FILE: /run/secrets/api_mailer_password
      MAILER_ENCRYPTION: tls
      MAILER_FROM_EMAIL: ${API_MAILER_FROM_EMAIL}
      FRONTEND_URL: https://demo-auction.deworker.pro
      SENTRY_DSN_FILE: /run/secrets/sentry_dsn
      JWT_ENCRYPTION_KEY_FILE: /run/secrets/jwt_encryption_key
      JWT_PUBLIC_KEY_PATH: /run/secrets/jwt_public_key
      JWT_PRIVATE_KEY_PATH: /run/secrets/jwt_private_key
    secrets:
      - api_db_password
      - api_mailer_password
      - sentry_dsn
      - jwt_encryption_key
      - jwt_public_key
      - jwt_private_key

  api-postgres:
    image: postgres:13.3-alpine
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD_FILE: /run/secrets/api_db_password
      POSTGRES_DB: app
    secrets:
      - api_db_password
    volumes:
      - api-postgres:/var/lib/postgresql/data

secrets:
  api_db_password:
    file: ./secrets/api_db_password
  api_mailer_password:
    file: ./secrets/api_mailer_password
  sentry_dsn:
    file: ./secrets/sentry_dsn
  jwt_encryption_key:
    file: ./secrets/jwt_encryption_key
  jwt_public_key:
    file: ./secrets/jwt_public_key
  jwt_private_key:
    file: ./secrets/jwt_private_key

volumes:
  api-postgres:
