version: "3.7"
services:
  gateway:
    image: ${REGISTRY}/auction-gateway:${IMAGE_TAG}
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/html:/var/www/html:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - api

  frontend:
    image: ${REGISTRY}/auction-frontend:${IMAGE_TAG}
    restart: always

  api:
    image: ${REGISTRY}/auction-api:${IMAGE_TAG}
    restart: always
    depends_on:
      - api-php-fpm

  api-php-fpm:
    image: ${REGISTRY}/auction-api-php-fpm:${IMAGE_TAG}
    restart: always
    environment:
      APP_ENV: prod
      APP_DEBUG: 0
      DB_HOST: api-postgres
      DB_USER: api
      DB_PASSWORD: ${API_DB_PASSWORD}
      DB_NAME: app

  api-cli-fpm:
    image: ${REGISTRY}/auction-api-php-cli:${IMAGE_TAG}
    restart: always
    environment:
      APP_ENV: prod
      APP_DEBUG: 0
      DB_HOST: api-postgres
      DB_USER: api
      DB_PASSWORD: ${API_DB_PASSWORD}
      DB_NAME: app

  api-postgres:
    image: postgres:12.2-alpine
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: ${API_DB_PASSWORD}
      POSTGERS_DB: app
    volumes:
      - api-postgress:/var/lib/postgresql/data

volumes:
  api-postgress:
