version: "3.7"
services:
  gateway:
    build:
      context: gateway/docker
      dockerfile: development/nginx/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
    depends_on:
      - frontend
      - api
      - mailer

  frontend:
    build:
      context: frontend/docker/development/nginx
    depends_on:
          - frontend-node

  frontend-node:
    build:
      context: frontend/docker/development/node
    volumes:
      - ./frontend:/app
    command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && yarn start"
    tty: true

  frontend-node-cli:
    build:
      context: frontend/docker/development/node
    volumes:
      - ./frontend:/app

  api:
    build:
      context: api/docker
      dockerfile: development/nginx/Dockerfile
    volumes:
      - ./api:/app
    depends_on:
      - api-php-fpm

  api-php-fpm:
    build:
      context: api/docker
      dockerfile: development/php-fpm/Dockerfile
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      PHP_IDE_CONFIG: serverName=API
      DB_HOST: api-postgres
      DB_USER: app
      DB_PASSWORD_FILE: /run/secrets/api_db_password
      DB_NAME: app
      MAILER_HOST: mailer
      MAILER_PORT: 1025
      MAILER_USERNAME: app
      MAILER_PASSWORD_FILE: /run/secrets/api_mailer_password
      MAILER_ENCRYPTION: tcp
      MAILER_FROM_EMAIL: mail@app.test
      FRONTEND_URL: http://localhost:8080
      SENTRY_DSN_FILE: /run/secrets/sentry_dsn
      JWT_ENCRYPTION_KEY_FILE: /run/secrets/jwt_encryption_key
      JWT_PUBLIC_KEY_PATH: /run/secrets/jwt_public_key
      JWT_PRIVATE_KEY_PATH: /run/secrets/jwt_private_key
    volumes:
      - ./api:/app
    secrets:
      - api_db_password
      - api_mailer_password
      - sentry_dsn
      - jwt_encryption_key
      - jwt_public_key
      - jwt_private_key

  api-php-cli:
    build:
      context: api/docker
      dockerfile: development/php-cli/Dockerfile
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      DB_HOST: api-postgres
      DB_USER: app
      DB_PASSWORD_FILE: /run/secrets/api_db_password
      DB_NAME: app
      MAILER_HOST: mailer
      MAILER_PORT: 1025
      MAILER_USERNAME: app
      MAILER_PASSWORD_FILE: /run/secrets/api_mailer_password
      MAILER_ENCRYPTION: tcp
      MAILER_FROM_EMAIL: mail@app.test
      FRONTEND_URL: http://localhost:8080
      SENTRY_DSN_FILE: /run/secrets/sentry_dsn
      JWT_ENCRYPTION_KEY_FILE: /run/secrets/jwt_encryption_key
      JWT_PUBLIC_KEY_PATH: /run/secrets/jwt_public_key
      JWT_PRIVATE_KEY_PATH: /run/secrets/jwt_private_key
    volumes:
      - ./api:/app
    secrets:
      - api_db_password
      - api_mailer_password
      - sentry_dsn
      - jwt_encryption_key
      - jwt_public_key
      - jwt_private_key

  api-postgres:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD_FILE: /run/secrets/api_db_password
      POSTGRES_DB: app
    secrets:
      - api_db_password
    volumes:
      - api-postgres:/var/lib/postgresql/data
    ports:
      - "54321:5432"

  mailer:
    image: mailhog/mailhog

  cucumber-node-cli:
    build:
      context: cucumber/docker/development/node
    volumes:
      - ./cucumber:/app

secrets:
  api_db_password:
    file: ./docker/development/secrets/api_db_password
  api_mailer_password:
    file: ./docker/development/secrets/api_mailer_password
  sentry_dsn:
    file: ./docker/development/secrets/sentry_dsn
  jwt_encryption_key:
    file: ./docker/development/secrets/jwt_encryption_key
  jwt_public_key:
    file: ./docker/development/secrets/jwt_public_key
  jwt_private_key:
    file: ./docker/development/secrets/jwt_private_key

volumes:
  api-postgres:
