version: "3.7"
services:
  gateway:
    image: ${REGISTRY}/auction-testing-gateway:${IMAGE_TAG}
    depends_on:
      - frontend
      - api
      - mailer

  frontend:
    image: ${REGISTRY}/auction-frontend:${IMAGE_TAG}

  api:
    image: ${REGISTRY}/auction-api:${IMAGE_TAG}
    depends_on:
      - api-php-fpm

  api-php-fpm:
    image: ${REGISTRY}/auction-api-php-fpm:${IMAGE_TAG}
    environment:
      APP_ENV: prod
      APP_DEBUG: 0
      DB_HOST: api-postgres
      DB_USER: app
      DB_PASSWORD_FILE: /run/secrets/api_db_password
      DB_NAME: app
      MAILER_HOST: mailer
      MAILER_PORT: 1025
      MAILER_USERNAME: app
      MAILER_PASSWORD_FILE: /run/secrets/api_mailer_password
      MAILER_ENCRYPTION: tcp
      MAILER_FROM_EMAIL: mail@app.test
      FRONTEND_URL: http://gateway:8080
      SENTRY_DSN_FILE: /run/secrets/sentry_dsn
      JWT_ENCRYPTION_KEY_FILE: /run/secrets/jwt_encryption_key
      JWT_PUBLIC_KEY_PATH: /run/secrets/jwt_public_key
      JWT_PRIVATE_KEY_PATH: /run/secrets/jwt_private_key
    secrets:
      - api_db_password
      - api_mailer_password
      - sentry_dsn
      - jwt_encryption_key
      - jwt_public_key
      - jwt_private_key

  api-php-cli:
    image: ${REGISTRY}/auction-api-php-cli:${IMAGE_TAG}
    environment:
      APP_ENV: prod
      APP_DEBUG: 0
      DB_HOST: api-postgres
      DB_USER: app
      DB_PASSWORD_FILE: /run/secrets/api_db_password
      DB_NAME: app
      MAILER_HOST: mailer
      MAILER_PORT: 1025
      MAILER_USERNAME: app
      MAILER_PASSWORD_FILE: /run/secrets/api_mailer_password
      MAILER_ENCRYPTION: tcp
      MAILER_FROM_EMAIL: mail@app.test
      FRONTEND_URL: http://gateway:8080
      SENTRY_DSN_FILE: /run/secrets/sentry_dsn
      JWT_ENCRYPTION_KEY_FILE: /run/secrets/jwt_encryption_key
      JWT_PUBLIC_KEY_PATH: /run/secrets/jwt_public_key
      JWT_PRIVATE_KEY_PATH: /run/secrets/jwt_private_key
    secrets:
      - api_db_password
      - api_mailer_password
      - sentry_dsn
      - jwt_encryption_key
      - jwt_public_key
      - jwt_private_key

  testing-api-php-cli:
    image: ${REGISTRY}/auction-testing-api-php-cli:${IMAGE_TAG}
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      DB_HOST: api-postgres
      DB_USER: app
      DB_PASSWORD_FILE: /run/secrets/api_db_password
      DB_NAME: app
      MAILER_HOST: mailer
      MAILER_PORT: 1025
      MAILER_USERNAME: app
      MAILER_PASSWORD_FILE: /run/secrets/api_mailer_password
      MAILER_ENCRYPTION: tcp
      MAILER_FROM_EMAIL: mail@app.test
      FRONTEND_URL: http://gateway:8080
      SENTRY_DSN_FILE: /run/secrets/sentry_dsn
      JWT_ENCRYPTION_KEY_FILE: /run/secrets/jwt_encryption_key
      JWT_PUBLIC_KEY_PATH: /run/secrets/jwt_public_key
      JWT_PRIVATE_KEY_PATH: /run/secrets/jwt_private_key
    secrets:
      - api_db_password
      - api_mailer_password
      - sentry_dsn
      - jwt_encryption_key
      - jwt_public_key
      - jwt_private_key

  api-postgres:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD_FILE: /run/secrets/api_db_password
      POSTGRES_DB: app
    secrets:
      - api_db_password

  mailer:
    image: mailhog/mailhog

  cucumber-node-cli:
    image: ${REGISTRY}/auction-cucumber-node-cli:${IMAGE_TAG}
    volumes:
      - ./cucumber/var:/app/var

secrets:
  api_db_password:
    file: ./docker/development/secrets/api_db_password
  api_mailer_password:
    file: ./docker/development/secrets/api_mailer_password
  sentry_dsn:
    file: ./docker/development/secrets/sentry_dsn
  jwt_encryption_key:
    file: ./docker/development/secrets/jwt_encryption_key
  jwt_public_key:
    file: ./docker/development/secrets/jwt_public_key
  jwt_private_key:
    file: ./docker/development/secrets/jwt_private_key
