site:
	ansible-playbook site.yml -i hosts.yml

renew-certificate:
	ansible-playbook renew-cerificate.yml -i hosts.yml

authorize:
	ansible-playbook authorize.yml -i hosts.yml

docker-login:
	ansible-playbook docker-login.yml -i hosts.yml
